const { v4 } = require("uuid");

module.exports = [
  {
    id: v4(),
    type: "food",
    name: "Tomato",
    image: "images/tomato.jpg",
    price: 3,
    currency: "BGN",
    amount: 1,
    unit: "KG",
  },
  {
    id: v4(),
    type: "food",
    name: "Bread",
    image: "images/bread.jpg",
    price: 1.5,
    currency: "BGN",
    amount: 0.5,
    unit: "KG",
  },
  {
    id: v4(),
    type: "food",
    name: "Cheese",
    image: "images/cheese.jpg",
    price: 12,
    currency: "BGN",
    amount: 1,
    unit: "KG",
  },
  {
    id: v4(),
    type: "food",
    name: "Sunflower oil",
    image: "images/sunflower-oil.jpg",
    price: 8,
    currency: "BGN",
    amount: 1,
    unit: "l",
  },
  {
    id: v4(),
    type: "food",
    name: "Cucumber",
    image: "images/cucumber.jpg",
    price: 4,
    currency: "BGN",
    amount: 1,
    unit: "KG",
  },
  {
    id: v4(),
    type: "food",
    name: "Potato",
    image: "images/potato.jpg",
    price: 3,
    currency: "BGN",
    amount: 1,
    unit: "KG",
  },
  {
    id: v4(),
    type: "food",
    name: "Beans",
    image: "images/beans.jpg",
    price: 4,
    currency: "BGN",
    amount: 0.5,
    unit: "KG",
  },
  {
    id: v4(),
    type: "drink",
    name: "Water",
    image: "images/water.jpg",
    price: 0.5,
    currency: "BGN",
    amount: 1,
    unit: "",
  },
  {
    id: v4(),
    type: "drink",
    name: "Milk",
    image: "images/milk.jpg",
    price: 2,
    currency: "BGN",
    amount: 1,
    unit: "l",
  },
  {
    id: v4(),
    type: "drink",
    name: "Orange juice",
    image: "images/orange-juice.jpg",
    price: 1.5,
    currency: "BGN",
    amount: 1,
    unit: "l",
  },
  {
    id: v4(),
    type: "drink",
    name: "Apple juice",
    image: "images/apple-juice.jpg",
    price: 1.4,
    currency: "BGN",
    amount: 1,
    unit: "l",
  },
  {
    id: v4(),
    type: "drink",
    name: "Rakia",
    image: "images/rakia.jpg",
    price: 12,
    currency: "BGN",
    amount: 1,
    unit: "l",
  },
  {
    id: v4(),
    type: "drink",
    name: "Wine",
    image: "images/wine.jpg",
    price: 20,
    currency: "BGN",
    amount: 1,
    unit: "l",
  },
  {
    id: v4(),
    type: "drink",
    name: "Beer",
    image: "images/beer.jpg",
    price: 2,
    currency: "BGN",
    amount: 0.5,
    unit: "l",
  },
];
