
module.exports = [
  {
    id: 1,
    type: "food",
    name: "Tomato",
    image: "http://localhost:8080/images/tomato.jpg",
    price: 3,
    currency: "BGN",
    amount: 1,
    unit: "KG",
  },
  {
    id: 2,
    type: "food",
    name: "Bread",
    image: "http://localhost:8080/images/bread.jpg",
    price: 1.5,
    currency: "BGN",
    amount: 0.5,
    unit: "KG",
  },
  {
    id: 3,
    type: "food",
    name: "Cheese",
    image: "http://localhost:8080/images/cheese.jpg",
    price: 12,
    currency: "BGN",
    amount: 1,
    unit: "KG",
  },
  {
    id: 4,
    type: "food",
    name: "Sunflower oil",
    image: "http://localhost:8080/images/sunflower-oil.jpg",
    price: 8,
    currency: "BGN",
    amount: 1,
    unit: "l",
  },
  {
    id: 5,
    type: "food",
    name: "Cucumber",
    image: "http://localhost:8080/images/cucumber.jpg",
    price: 4,
    currency: "BGN",
    amount: 1,
    unit: "KG",
  },
  {
    id: 6,
    type: "food",
    name: "Potato",
    image: "http://localhost:8080/images/potato.jpg",
    price: 3,
    currency: "BGN",
    amount: 1,
    unit: "KG",
  },
  {
    id: 7,
    type: "food",
    name: "Beans",
    image: "http://localhost:8080/images/beans.jpg",
    price: 4,
    currency: "BGN",
    amount: 0.5,
    unit: "KG",
  },
  {
    id: 8,
    type: "drink",
    name: "Water",
    image: "http://localhost:8080/images/water.jpg",
    price: 0.5,
    currency: "BGN",
    amount: 1,
    unit: "",
  },
  {
    id: 9,
    type: "drink",
    name: "Milk",
    image: "http://localhost:8080/images/milk.jpg",
    price: 2,
    currency: "BGN",
    amount: 1,
    unit: "l",
  },
  {
    id: 10,
    type: "drink",
    name: "Orange juice",
    image: "http://localhost:8080/images/orange-juice.jpg",
    price: 1.5,
    currency: "BGN",
    amount: 1,
    unit: "l",
  },
  {
    id: 11,
    type: "drink",
    name: "Apple juice",
    image: "http://localhost:8080/images/apple-juice.jpg",
    price: 1.4,
    currency: "BGN",
    amount: 1,
    unit: "l",
  },
  {
    id: 12,
    type: "drink",
    name: "Rakia",
    image: "http://localhost:8080/images/rakia.jpg",
    price: 12,
    currency: "BGN",
    amount: 1,
    unit: "l",
  },
  {
    id: 13,
    type: "drink",
    name: "Wine",
    image: "http://localhost:8080/images/wine.jpg",
    price: 20,
    currency: "BGN",
    amount: 1,
    unit: "l",
  },
  {
    id: 14,
    type: "drink",
    name: "Beer",
    image: "http://localhost:8080/images/beer.jpg",
    price: 2,
    currency: "BGN",
    amount: 0.5,
    unit: "l",
  },
];
